name: Run Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r QuestionBoxBot-repo/requirements.txt

      - name: Run bot
        run: |
          python QuestionBoxBot-repo/main.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # GitHub Secretsからトークンを取得
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}  # GitHub SecretsからチャンネルIDを取得
