name: Deploy QuestionBox Bot

on:
  push:
    branches:
      - main  # デプロイを実行するブランチ
  schedule:
    - cron: "0 */6 * * *"  # 6時間ごとにジョブを実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # GitHub Secretsから環境変数を設定
      - name: Set environment variables
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV
          echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}" >> $GITHUB_ENV

      # `main.py` のあるディレクトリに移動してから実行
      - name: Run bot
        run: |
          cd discord_qustion_bot
          python main.py
